/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import code.Cadastrados;
import code.excecaoCadastrados;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Henrique
 */
public class populacaoGUI extends javax.swing.JFrame {

    private Cadastrados cadastrados = new Cadastrados();

    public populacaoGUI() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMIResposta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMITotal = new javax.swing.JMenuItem();
        jMListaCadastrados = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMILimpar = new javax.swing.JMenuItem();
        jMISair = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastrar");

        jMIResposta.setText("Resposta");
        jMIResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRespostaActionPerformed(evt);
            }
        });
        jMenu1.add(jMIResposta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Listar");

        jMITotal.setText("Total  de Cadastrados");
        jMITotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMITotalActionPerformed(evt);
            }
        });
        jMenu2.add(jMITotal);

        jMListaCadastrados.setText("Lista de Cadastrados");
        jMListaCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMListaCadastradosActionPerformed(evt);
            }
        });
        jMenu2.add(jMListaCadastrados);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Opções");

        jMILimpar.setText("Limpar");
        jMILimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILimparActionPerformed(evt);
            }
        });
        jMenu3.add(jMILimpar);

        jMISair.setText("Sair");
        jMISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISairActionPerformed(evt);
            }
        });
        jMenu3.add(jMISair);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMISairActionPerformed

    private void jMIRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRespostaActionPerformed
        cadastroGUI respostas = new cadastroGUI(this, true, cadastrados);
        respostas.setVisible(true);

    }//GEN-LAST:event_jMIRespostaActionPerformed

    private void jMILimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILimparActionPerformed
        cadastrados = new Cadastrados();
    }//GEN-LAST:event_jMILimparActionPerformed

    private void jMITotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMITotalActionPerformed
        JOptionPane.showMessageDialog(this, "O total de cadastrados é: " + cadastrados.totalPessoas(), "Total de Pessoas", 0);
    }//GEN-LAST:event_jMITotalActionPerformed

    private void jMListaCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMListaCadastradosActionPerformed
       
          try {
            cadastrados.checagemCadastrados();
            listaEmailGUI r = new listaEmailGUI(this, true, cadastrados);
        r.setVisible(true);
        } catch (excecaoCadastrados exC) {
            JOptionPane.showMessageDialog(this, "Não há cadastrados", "Warning", 0);
        }
       
                   
    }//GEN-LAST:event_jMListaCadastradosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(populacaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(populacaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(populacaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(populacaoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new populacaoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenuItem jMILimpar;
    private javax.swing.JMenuItem jMIResposta;
    private javax.swing.JMenuItem jMISair;
    private javax.swing.JMenuItem jMITotal;
    private javax.swing.JMenuItem jMListaCadastrados;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
